In [1]:
import pandas as pd

In [2]:
ad_data = pd.read_csv('./data/fb_last_90_days_ad.csv')

In [3]:
ad_data.head()

,Page ID,Page Name,Disclaimer,Amount Spent (USD),Number of Ads in Library
0,6756153498,Mike Bloomberg,Mike Bloomberg 2020 Inc,61113409,179824
1,416707608450706,Tom Steyer,TOM STEYER 2020,9687496,3052
2,153080620724,Donald J. Trump,TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE,7540896,95233
3,124955570892789,Bernie Sanders,BERNIE 2020,6592055,17498
4,38471053686,Elizabeth Warren,"WARREN FOR PRESIDENT, INC.",3489548,13803

In [4]:
# Since names could be written differently, we just look up using firt and last name of candidates 
candidates = {
    'joe': 'Joe Biden',
    'biden': 'Joe Biden',
    'donald': 'Donald Trump', 
    'trump': 'Donald Trump', 
    'bernie': 'Bernie Sanders',
    'sanders': 'Bernie Sanders',
    'elizabeth': 'Elizabeth Warren',
    'warren': 'Elizabeth Warren',
    'mike': 'Mike Bloomberg',
    'bloomberg':'Mike Bloomberg',
    'pete': 'Pete Buttigieg',
    'buttigieg': 'Pete, Buttigieg',
    'andrew': 'Andrew Yang', 
    'yang': 'Andrew Yang'
}

election_ad_data = ad_data.loc[ad_data['Page Name'].str.contains('|'.join(candidates.keys()), case=False, regex=True)]
election_ad_data.head()

,Page ID,Page Name,Disclaimer,Amount Spent (USD),Number of Ads in Library
0,6756153498,Mike Bloomberg,Mike Bloomberg 2020 Inc,61113409,179824
2,153080620724,Donald J. Trump,TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE,7540896,95233
3,124955570892789,Bernie Sanders,BERNIE 2020,6592055,17498
4,38471053686,Elizabeth Warren,"WARREN FOR PRESIDENT, INC.",3489548,13803
5,7860876103,Joe Biden,BIDEN FOR PRESIDENT,3007690,4424

In [5]:
def standardizeCandidateName(name):
    for candidate_name, candidate_full_name in candidates.items():
        if candidate_name in name.lower():
            return candidate_full_name
    return np.nan

election_ad_data['candidate'] = election_ad_data['Page Name'].apply(standardizeCandidateName)
election_ad_data.head(20)

/Users/danielshiferaw/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,Page ID,Page Name,Disclaimer,Amount Spent (USD),Number of Ads in Library,candidate
0,6756153498,Mike Bloomberg,Mike Bloomberg 2020 Inc,61113409,179824,Mike Bloomberg
2,153080620724,Donald J. Trump,TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE,7540896,95233,Donald Trump
3,124955570892789,Bernie Sanders,BERNIE 2020,6592055,17498,Bernie Sanders
4,38471053686,Elizabeth Warren,"WARREN FOR PRESIDENT, INC.",3489548,13803,Elizabeth Warren
5,7860876103,Joe Biden,BIDEN FOR PRESIDENT,3007690,4424,Joe Biden
6,1039701332716228,Pete Buttigieg,"PETE FOR AMERICA, INC.",2647964,41151,Pete Buttigieg
12,153080620724,Donald J. Trump,"DONALD J. TRUMP FOR PRESIDENT, INC.",1827600,67078,Donald Trump
14,106927400764857,Team Mike 2020,Mike Bloomberg 2020 Inc,1318814,273,Mike Bloomberg
29,6726182861,Mike Pence,TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE,740949,5832,Mike Bloomberg
51,562149327457702,Andrew Yang,FRIENDS OF ANDREW YANG,536908,2699,Andrew Yang
107,1487587521541634,President Donald Trump Fan Club,I Love My Freedom,274507,658,Donald Trump
218,102618334589524,California for Mike,Mike Bloomberg 2020 Inc,128793,32,Mike Bloomberg
219,106111517569034,TX for Mike,Mike Bloomberg 2020 Inc,128710,34,Mike Bloomberg
251,104456297747947,FL for Mike,Mike Bloomberg 2020 Inc,109959,17,Mike Bloomberg
272,104233224437484,Colorado for Mike Bloomberg,Mike Bloomberg 2020 Inc,101624,22,Mike Bloomberg
276,105998470924827,VA for Mike,Mike Bloomberg 2020 Inc,100344,19,Mike Bloomberg
278,105953917589790,TN for Mike,Mike Bloomberg 2020 Inc,99412,27,Mike Bloomberg
281,101452724694651,N.C. for Mike,Mike Bloomberg 2020 Inc,98564,22,Mike Bloomberg
285,6713653788,Gary Peters,PETERS FOR MICHIGAN,97271,246,Pete Buttigieg
298,1487587521541634,President Donald Trump Fan Club,Making Web LLC,92552,33,Donald Trump

In [19]:
affiliates = election_ad_data[['Disclaimer', 'candidate']].reset_index()
affiliates.drop(columns=['index'], inplace=True)
affiliates.drop_duplicates(inplace=True)
affiliates.drop(index=affiliates[affiliates['Disclaimer'] == 'These ads ran without a disclaimer'].index, inplace=True)
affiliates.rename(columns={'Disclaimer': 'affiliate_name', 'candidate': 'candidate_name'}, inplace=True)
affiliates.index.name = 'affiliate_id'
affiliates.head(10)

                                        affiliate_name    candidate_name
affiliate_id
0                              Mike Bloomberg 2020 Inc    Mike Bloomberg
1             TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE      Donald Trump
2                                          BERNIE 2020    Bernie Sanders
3                           WARREN FOR PRESIDENT, INC.  Elizabeth Warren
4                                  BIDEN FOR PRESIDENT         Joe Biden
5                               PETE FOR AMERICA, INC.    Pete Buttigieg
6                  DONALD J. TRUMP FOR PRESIDENT, INC.      Donald Trump
8             TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE    Mike Bloomberg
9                               FRIENDS OF ANDREW YANG       Andrew Yang
10                                   I Love My Freedom      Donald Trump

In [20]:
states = pd.read_csv('./data/state_entity.csv')
states

   1     California  CA  39510000  415  75277  36.7
0  2       New York  NY  19450000   81  64894  38.2
1  3     Washington  WA   7615000   89  74073  38.3
2  4        Arizona  AZ   7290000   78  59246  38.0
3  5   Pennsylvania  PA  12800000  153  60905  40.8
4  6        Vermont  VT    623989   11  57513  42.7
5  7  Massachusetts  MA   6893000   91  77385  39.5
6  8        Indiana  IN   6732000   89  54181  37.4

In [21]:
platform = pd.read_csv('./data/platform_entity.csv')
platform.head()

   platform_id platform_name platform_type
0            1      Facebook       Digital
1            2        Google       Digital
2            3          Hulu            TV

In [22]:
candidate_entity = pd.read_csv('./data/candidate.csv')
candidate_entity.to_csv('./data/candidate_entity.csv', index=False)
candidate_entity

,candidate_id,candidate_name,birthday,home_state_id,election_year,party
0,1,Joe Biden,11/20/1942,5,2020,Democrat
1,2,Donald Trump,14/06/1946,2,2020,Republican
2,3,Bernie Sanders,09/08/1941,6,2020,Democrat
3,4,Elizabeth Warren,05/22/1949,7,2020,Democrat
4,5,Mike Bloomberg,02/14/1942,2,2020,Independent
5,6,Pete Buttigieg,01/19/1982,8,2020,Democrat
6,7,Andrew Yang,01/13/1975,2,2020,Democrat

In [27]:
affiliate_entity = affiliates.merge(candidate_entity)
# affiliate_entity = affiliate_entity[['affiliate_name', 'candidate_id']]
affiliate_entity.head()

,affiliate_name,candidate_name,candidate_id,birthday,home_state_id,election_year,party
0,Mike Bloomberg 2020 Inc,Mike Bloomberg,5,02/14/1942,2,2020,Independent
1,TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE,Mike Bloomberg,5,02/14/1942,2,2020,Independent
2,"DONALD J. TRUMP FOR PRESIDENT, INC.",Mike Bloomberg,5,02/14/1942,2,2020,Independent
3,DCCC. (202) 863-1500. Not authorized by any ca...,Mike Bloomberg,5,02/14/1942,2,2020,Independent
4,QuickTake by Bloomberg,Mike Bloomberg,5,02/14/1942,2,2020,Independent

In [272]:
polling_data = pd.read_csv('./data/primary_poll_2020.csv')
polling_data.head()

,race,state,modeldate,candidate_name,pct_estimate,pct_trend_adjusted,timestamp,contestdate
0,2020D,Wyoming,3/3/2020,Tulsi Gabbard,4.010000e-07,0.133615,08:30:45 3 Mar 2020,4/4/2020
1,2020D,Wisconsin,3/3/2020,Tulsi Gabbard,1.435704e+00,1.452380,08:30:45 3 Mar 2020,4/7/2020
2,2020D,Washington,3/3/2020,Tulsi Gabbard,4.351059e-01,0.500738,08:30:45 3 Mar 2020,3/10/2020
3,2020D,Virginia,3/3/2020,Tulsi Gabbard,4.796470e-01,0.475446,08:30:45 3 Mar 2020,3/3/2020
4,2020D,Vermont,3/3/2020,Tulsi Gabbard,9.796870e-01,0.940180,08:30:45 3 Mar 2020,3/3/2020

In [273]:
polling_data.drop(columns=['race', 'modeldate', 'pct_estimate', 'timestamp'], inplace=True)

In [274]:
select_poll_data = polling_data.loc[polling_data['candidate_name'].str.contains('|'.join(candidates.keys()), case=False, regex=True)]
select_poll_data.reset_index(inplace=True)
select_poll_data.drop(columns=['index'], inplace=True)
select_poll_data.rename(columns={'pct_trend_adjusted': 'result', 'contestdate': 'Contest Date'}, inplace=True)
select_poll_data['candidate_name'] = select_poll_data['candidate_name'].apply(standardizeCandidateName)
select_poll_data.dropna(inplace=True)
select_poll_data

/Users/danielshiferaw/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/danielshiferaw/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                state  candidate_name     result Contest Date
0           Wisconsin  Mike Bloomberg  14.806040     4/7/2020
1          Washington  Mike Bloomberg  15.807920    3/10/2020
2            Virginia  Mike Bloomberg  14.627430     3/3/2020
3             Vermont  Mike Bloomberg   8.890288     3/3/2020
4                Utah  Mike Bloomberg  18.164300     3/3/2020
...               ...             ...        ...          ...
54592   New Hampshire  Bernie Sanders  25.829024    2/11/2020
54594      California  Bernie Sanders  21.407151     3/3/2020
54595  South Carolina       Joe Biden  42.682725    2/29/2020
54596   New Hampshire       Joe Biden  26.240704    2/11/2020
54598      California       Joe Biden  33.476835     3/3/2020

[52123 rows x 4 columns]

In [275]:
final_poll_entity = candidate_entity.merge(select_poll_data, how='inner', on='candidate_name').merge(states, how='inner', left_on='state', right_on='state_name')
final_poll_entity = final_poll_entity[['state_id', 'candidate_id', 'Contest Date', 'result']]
final_poll_entity = final_poll_entity.groupby(['state_id', 'candidate_id', 'Contest Date'], as_index=False).agg({'result':max})
final_poll_entity.rename(columns={'Contest Date': 'contest_date'}, inplace=True)
final_poll_entity.index.name = 'poll_id'
final_poll_entity.head()

         state_id  candidate_id contest_date     result
poll_id
0               1             1     3/3/2020  33.476835
1               1             3     3/3/2020  34.197440
2               1             4     3/3/2020  27.234257
3               1             5     3/3/2020  16.014110
4               1             6     3/3/2020  12.345886

In [276]:
final_poll_entity.to_csv('./data/poll_entity.csv')